import Link from 'next/link'
import './globals.scss'
import { Roboto_Mono } from 'next/font/google'

const robotoMono = Roboto_Mono({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body className={robotoMono.className}>
        <header>
          <h1>Fukurou GPT</h1>
        </header>
        <nav>
          <ul>
            <li>
              <Link href="translator-for-dev3">
                <p>Translator</p>
                <span>for dev3</span>
              </Link>
            </li>
            <li>
              <Link href="translator-for-dev3">
                <p>Dummy</p>
                <span>dummy page</span>
              </Link>
            </li>
          </ul>
        </nav>
        <div className="contents">
          {children}
        </div>
      </body>
    </html>
  )
}
